# Generated by Django 5.2.5 on 2025-09-04 06:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table_comment': 'Будьте внимательны! Удаление наименования приведёт к удалению всех записей о ДДС, включающих данное наименование. Внесите необходимые корректировки до удаления.',
                'ordering': ('type', 'name'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
                'db_table_comment': 'Будьте внимательны! Удаление наименования приведёт к удалению всех записей о ДДС, включающих данное наименование. Внесите необходимые корректировки до удаления.',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
                'db_table_comment': 'Будьте внимательны! Удаление наименования приведёт к удалению всех записей о ДДС, включающих данное наименование. Внесите необходимые корректировки до удаления.',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Наименование')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
                'db_table_comment': 'Будьте внимательны! Удаление наименования приведёт к удалению всех записей о ДДС, включающих данное наименование. Внесите необходимые корректировки до удаления.',
                'ordering': ('category', 'name'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('amount', models.PositiveBigIntegerField(help_text='Количество средств в рублях', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Сумма')),
                ('comment', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.category', verbose_name='Категория')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.status', verbose_name='Статус')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.subcategory', verbose_name='Подкатегория')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.type', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'db_table_comment': 'Полужирным шрифтом отмечены поля, обязательные для заполнения, обычным шрифтом – необязательные.',
                'ordering': ('-created_at',),
                'default_related_name': 'records',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.type', verbose_name='Тип'),
        ),
    ]
