# Generated by Django 5.2.5 on 2025-09-05 11:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'статус',
                'verbose_name_plural': 'Статусы',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'тип',
                'verbose_name_plural': 'Типы',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Наименование')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'подкатегория',
                'verbose_name_plural': 'Подкатегории',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Дата создания записи')),
                ('amount', models.PositiveBigIntegerField(help_text='Количество средств в рублях.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Сумма')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.status', verbose_name='Статус')),
                ('subcategory', models.ForeignKey(help_text='Доступен поиск по подкатегориям, категориям и типам.', on_delete=django.db.models.deletion.CASCADE, to='records.subcategory', verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'запись',
                'verbose_name_plural': 'Записи',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.type', verbose_name='Тип'),
        ),
    ]
